<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Genesis.Template2D</RootNamespace>
    <PackageId>Genesis.Template2D</PackageId>
    <Version>0.0.1</Version>
    <Authors>Genesis Engine Team</Authors>
    <Description>Genesis 2D 沙盒项目模板</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\projects\Genesis\Genesis.csproj" />
    <ProjectReference Include="..\..\..\Gnosis.cs\projects\Gnosis.ECS\Gnosis.ECS.csproj" />
    <ProjectReference Include="..\..\..\Gnosis.cs\projects\Gnosis.Core\Gnosis.Core.csproj" />
  </ItemGroup>

</Project>
